#!/usr/bin/env bash
# setup.sh — one-time setup that creates the Bazel package inside LiteRT-LM
# and builds libLiteRtLmEngine.so/.dylib.
#
# Safe to re-run: all steps are idempotent.
#
# Usage:
#   ./setup.sh                  # uses LiteRT-LM/ submodule
#   LITERT_DIR=/my/path ./setup.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LITERT_DIR="${LITERT_DIR:-${SCRIPT_DIR}/LiteRT-LM}"

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if [[ ! -f "${LITERT_DIR}/WORKSPACE" ]]; then
  echo "ERROR: LiteRT-LM not found at ${LITERT_DIR}"
  echo "Run: git submodule update --init --recursive"
  exit 1
fi

if ! command -v bazelisk &>/dev/null; then
  echo "ERROR: bazelisk not found. Install with: brew install bazelisk"
  exit 1
fi

PKG_DIR="${LITERT_DIR}/lite_inference_server"

# ---------------------------------------------------------------------------
# 1. Copy server sources into LiteRT-LM as a Bazel package
# ---------------------------------------------------------------------------
echo "→ Syncing server sources into ${PKG_DIR} ..."
mkdir -p "${PKG_DIR}"

# Copy source files (not the BUILD — that's managed below).
for f in \
  "core/engine.h" \
  "core/litert/llm_engine.h" \
  "core/litert/llm_engine.cc" \
  "core/litert/webgpu_sampler_shim.c" \
  "hub/model_resolver.h" \
  "hub/model_resolver.cc" \
  "server/main.cc" \
  "server/rest/openai_api.h" \
  "server/rest/openai_api.cc"
do
  src="${SCRIPT_DIR}/${f}"
  rel_dir=$(dirname "${f}")
  dest_dir="${PKG_DIR}/${rel_dir}"
  mkdir -p "${dest_dir}"
  cp -f "${src}" "${dest_dir}/"
done

# ---------------------------------------------------------------------------
# 2. Write BUILD file for the package
# ---------------------------------------------------------------------------
echo "→ Writing ${PKG_DIR}/BUILD ..."
cat > "${PKG_DIR}/BUILD" <<'BUILD_EOF'
# AUTO-GENERATED by setup.sh — do not edit by hand.
# Re-run ./setup.sh to regenerate.

package(default_visibility = ["//visibility:public"])

# Shared library exposing the LiteRT-LM C API.
# Consumed by the CMake build (server binary) and the Flutter FFI library.
# No srcs — engine.o is pulled in entirely via //c:engine (alwayslink=True).
cc_binary(
    name = "libLiteRtLmEngine.so",
    copts = ["-fvisibility=hidden"],
    features = ["-legacy_whole_archive"],
    linkopts = select({
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": [
            "-Wl,--no-undefined",
            "-Wl,--strip-all",
            "-Wl,--gc-sections",
            "-Wl,-Bsymbolic",
            "-Wl,-rpath,$$ORIGIN",
        ],
    }),
    linkshared = 1,
    deps = ["//c:engine"],
)

# Full inference server binary (HTTP + LLM).
cc_binary(
    name = "litert_server",
    srcs = [
        "server/main.cc",
        "server/rest/openai_api.h",
        "server/rest/openai_api.cc",
        "core/engine.h",
        "core/litert/llm_engine.h",
        "core/litert/llm_engine.cc",
        "core/litert/webgpu_sampler_shim.c",
        "hub/model_resolver.h",
        "hub/model_resolver.cc",
        "//c:engine.cc",
        "//c:engine.h",
    ],
    copts = [
        "-std=c++20",
        "-DCPPHTTPLIB_OPENSSL_SUPPORT",
    ],
    includes = ["."],
    linkopts = select({
        "@platforms//os:macos": ["-lssl", "-lcrypto"],
        "//conditions:default": ["-lssl", "-lcrypto"],
    }),
    deps = [
        "//c:engine",
        "@cpp_httplib//:httplib",
        "@nlohmann_json//:json",
    ],
)
BUILD_EOF

# ---------------------------------------------------------------------------
# 3. Patch WORKSPACE: add cpp-httplib if not already present
# ---------------------------------------------------------------------------
WORKSPACE="${LITERT_DIR}/WORKSPACE"

if ! grep -q '"cpp_httplib"' "${WORKSPACE}"; then
  echo "→ Patching WORKSPACE: adding cpp_httplib ..."

  # Fetch the real sha256 so the build is hermetic.
  HTTPLIB_URL="https://github.com/yhirose/cpp-httplib/archive/refs/tags/v0.18.3.tar.gz"
  echo "  Fetching sha256 for cpp-httplib v0.18.3 ..."
  if command -v sha256sum &>/dev/null; then
    HTTPLIB_SHA=$(curl -sL "${HTTPLIB_URL}" | sha256sum | awk '{print $1}')
  else
    HTTPLIB_SHA=$(curl -sL "${HTTPLIB_URL}" | shasum -a 256 | awk '{print $1}')
  fi
  echo "  sha256 = ${HTTPLIB_SHA}"

  cat >> "${WORKSPACE}" <<WORKSPACE_EOF

# Added by lite-inference setup.sh
http_archive(
    name = "cpp_httplib",
    build_file_content = """
cc_library(
    name = "httplib",
    hdrs = ["httplib.h"],
    visibility = ["//visibility:public"],
)
""",
    sha256 = "${HTTPLIB_SHA}",
    strip_prefix = "cpp-httplib-0.18.3",
    url = "${HTTPLIB_URL}",
)
WORKSPACE_EOF
else
  echo "→ WORKSPACE already contains cpp_httplib, skipping."
fi

# ---------------------------------------------------------------------------
# 4. Build libLiteRtLmEngine.so
# ---------------------------------------------------------------------------
if [[ "${SKIP_BAZEL_BUILD:-0}" == "1" ]]; then
  echo "→ Skipping Bazel build (SKIP_BAZEL_BUILD=1)."
else
  echo "→ Building libLiteRtLmEngine.so (this takes a few minutes the first time) ..."
  cd "${LITERT_DIR}"
  bazelisk build //lite_inference_server:libLiteRtLmEngine.so
fi

echo ""
echo "✓ Setup complete."
echo "  Library: ${LITERT_DIR}/bazel-bin/lite_inference_server/libLiteRtLmEngine.so"
echo ""
echo "Now build the CMake project:"
echo "  cmake -B build -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=\$(brew --prefix openssl)"
echo "  cmake --build build -j\$(sysctl -n hw.ncpu)"
